baseURL = 'https://sfndsn.github.io'
languageCode = 'en-us'
title = 'Sebastian Findeisen'
theme = 'hugo-coder-main'
[[menu.main]]
  name = "Research"
  weight = 1
  url  = "research/"
[[menu.main]]
  name = "Curriculum Vitae"
  weight = 2
  url = "cv/cv.pdf"
[[menu.main]]
  name = "Contact"
  weight = 3
  url = "contact/"
[params]
avatarURL = "images/findeisen.jpg"
author = "Sebastian Findeisen"
info = ["Professor of Economic Policy at the University of Konstanz"]
colorScheme = "auto"
[markup.goldmark.renderer]
  unsafe = true